# Generated by Django 4.2.9 on 2024-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="firstname",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="login",
            name="joined_date",
            field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="login",
            name="lastname",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="login",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
