# Generated by Django 4.2.9 on 2024-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_login_firstname_alter_login_joined_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="joined_date",
            field=models.DateField(blank=True, default="", null=True),
        ),
    ]
